from __future__ import annotations

import json
import math
import re
from pathlib import Path
from typing import Any, Mapping

from .models import RecipeParameter as LegacyRecipeParameter, WorkflowRecipe
from .recipes import (
    DiffReport,
    PreviewAdapter,
    PreviewRequest,
    Recipe,
    RecipeParameter,
    RecipeService,
    RecipeStep,
    RecipeVersion,
    canonical_json,
    canonicalize,
    compute_recipe_hash,
)

__all__ = [
    "DiffReport",
    "PreviewAdapter",
    "PreviewRequest",
    "Recipe",
    "RecipeParameter",
    "RecipeService",
    "RecipeStep",
    "RecipeVersion",
    "canonical_json",
    "canonicalize",
    "compute_recipe_hash",
    "generate_macro",
    "generate_report",
    "render_command",
    "write_artifacts",
]


_PLACEHOLDER = re.compile(r"\{\{([a-z][a-z0-9_]*)\}\}")
_NUMBER = re.compile(r"^[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?$")
_MACHINE_READY_OUTPUT = re.compile(
    r"(?:\bPOSTPROCESS\b|\bNC[_ ]?PROGRAM\b|\bG-?CODE\b|\bMACHINE[_ ]?CODE\b)",
    re.IGNORECASE,
)


def _format_parameter(parameter: LegacyRecipeParameter, value: Any) -> str:
    if parameter.value_type == "number":
        rendered = str(value)
        if not _NUMBER.match(rendered):
            raise ValueError(f"Parameter {parameter.name} must be numeric.")
        number = float(rendered)
        if not math.isfinite(number):
            raise ValueError(f"Parameter {parameter.name} must be finite.")
        return rendered

    rendered = str(value)
    if any(ord(char) < 32 for char in rendered):
        raise ValueError(f"Parameter {parameter.name} contains a control character.")
    quote = parameter.quote or "'"
    return quote + rendered.replace(quote, quote * 2) + quote


def render_command(
    template: str,
    parameters: list[LegacyRecipeParameter],
    overrides: Mapping[str, Any] | None = None,
) -> str:
    overrides = overrides or {}
    definitions = {parameter.name: parameter for parameter in parameters}

    def replace(match: re.Match[str]) -> str:
        name = match.group(1)
        if name not in definitions:
            raise ValueError(f"Template references unknown parameter {name}.")
        parameter = definitions[name]
        value = overrides.get(name, parameter.default)
        return _format_parameter(parameter, value)

    return _PLACEHOLDER.sub(replace, template)


def generate_macro(
    recipe: WorkflowRecipe,
    *,
    overrides: Mapping[str, Any] | None = None,
    allow_review_steps: bool = False,
) -> str:
    lines = [
        "// Generated by CAM Automation Lab",
        f"// Recipe: {recipe.name}",
        "// Review every command in PowerMill before execution.",
        "",
    ]
    for step in recipe.steps:
        if _MACHINE_READY_OUTPUT.search(
            " ".join((step.action, step.operation, step.template))
        ):
            lines.append(
                f"// BLOCKED {step.step_id}: machine-ready NC content omitted by policy"
            )
            continue
        command = render_command(step.template, recipe.parameters, overrides)
        if step.risk == "blocked":
            reason = ", ".join(step.reasons) or "blocked by policy"
            lines.append(f"// BLOCKED {step.step_id}: {reason}")
            lines.append(f"// {command}")
        elif step.risk == "review" and not allow_review_steps:
            reason = ", ".join(step.reasons) or "manual review required"
            lines.append(f"// REVIEW_REQUIRED {step.step_id}: {reason}")
            lines.append(f"// {command}")
        else:
            if step.risk == "review":
                lines.append(f"// REVIEW_ACCEPTED {step.step_id}")
            lines.append(command)
    lines.extend(["", "// End of generated workflow", ""])
    return "\n".join(lines)


def generate_report(parsed_count: int, recipe: WorkflowRecipe) -> str:
    review = [step for step in recipe.steps if step.risk == "review"]
    blocked = [step for step in recipe.steps if step.risk == "blocked"]
    lines = [
        f"# {recipe.name}",
        "",
        "## Summary",
        "",
        f"- Parsed commands: {parsed_count}",
        f"- Sessions analyzed: {recipe.sessions_analyzed}",
        f"- Sessions matched: {', '.join(recipe.sessions_matched)}",
        f"- Learned steps: {len(recipe.steps)}",
        f"- Learned parameters: {len(recipe.parameters)}",
        f"- Review-required steps: {len(review)}",
        f"- Blocked steps: {len(blocked)}",
        "",
        "## Parameters",
        "",
        "| Name | Type | Default | Samples |",
        "| --- | --- | --- | --- |",
    ]
    if recipe.parameters:
        for parameter in recipe.parameters:
            samples = ", ".join(str(item) for item in parameter.samples)
            lines.append(
                f"| `{parameter.name}` | {parameter.value_type} | "
                f"`{parameter.default}` | {samples} |"
            )
    else:
        lines.append("| _none_ |  |  |  |")

    lines.extend(
        [
            "",
            "## Steps",
            "",
            "| Step | Operation | Risk | Template |",
            "| --- | --- | --- | --- |",
        ]
    )
    for step in recipe.steps:
        escaped = step.template.replace("|", "\\|")
        lines.append(f"| {step.step_id} | {step.operation} | {step.risk} | `{escaped}` |")

    lines.extend(["", "## Diagnostics", ""])
    if recipe.diagnostics:
        lines.extend(f"- {item}" for item in recipe.diagnostics)
    else:
        lines.append("- No parser or alignment diagnostics.")
    lines.extend(
        [
            "",
            "> Generated macros are review artifacts. This demo never connects to PowerMill or "
            "executes commands.",
            "",
        ]
    )
    return "\n".join(lines)


def write_artifacts(
    output_dir: str | Path,
    *,
    parsed_count: int,
    recipe: WorkflowRecipe,
    overrides: Mapping[str, Any] | None = None,
    allow_review_steps: bool = False,
    activity_events: list[dict[str, Any]] | None = None,
) -> dict[str, Path]:
    destination = Path(output_dir)
    destination.mkdir(parents=True, exist_ok=True)
    paths = {
        "recipe": destination / "recipe.json",
        "macro": destination / "workflow.mac",
        "report": destination / "report.md",
    }
    if activity_events is not None:
        paths["events"] = destination / "events.jsonl"
    paths["recipe"].write_text(
        json.dumps(recipe.to_dict(), ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    paths["macro"].write_text(
        generate_macro(
            recipe,
            overrides=overrides,
            allow_review_steps=allow_review_steps,
        ),
        encoding="utf-8",
    )
    paths["report"].write_text(
        generate_report(parsed_count, recipe),
        encoding="utf-8",
    )
    if activity_events is not None:
        paths["events"].write_text(
            "".join(
                json.dumps(event, ensure_ascii=False, separators=(",", ":")) + "\n"
                for event in activity_events
            ),
            encoding="utf-8",
        )
    return paths
